name: Run WordPress Cron

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  cron:
    runs-on: ubuntu-latest

    steps:
      - name: Call WordPress cron
        run: |
          curl -A "Mozilla/5.0" https://tech-next-gen.lovestoblog.com/wp-cron.php?doing_wp_cron || true