name: Run WordPress Cron

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  cron:
    runs-on: ubuntu-latest

    steps:
      - name: Call WordPress cron
        run: |
          curl -I https://tech-next-gen.lovestoblog.com/wp-cron.php